from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.jsmn$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("JASMIIIIIIIIIIIIIINNNN.!!!")
        sleep(1)
        await e.edit("💝💘💓💗")
        sleep(1)
        await e.edit("💞💕💗💘")
        sleep(1)
        await e.edit("💝💘💓💗")
        sleep(1)
        await e.edit("💞💕💗💘")
        sleep(1)
        await e.edit("💘💞💗💕")
        sleep(1)
        await e.edit("💘💞💕💗")
        sleep(1)
        await e.edit("EMMMMMM🥺🥺🥺")
        sleep(1)
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("ICAL")
        sleep(1)
        await e.edit("SAYANG :')")
        sleep(1)
        await e.edit("JASMINE❣️❣️")
        sleep(1)
        await e.edit("💘💘💘💘")
        sleep(1)
        await e.edit("ELEPYUU JAMIIIINN💞💞")
        sleep(1)
        await e.edit("POKOKNYA ELEPYU PULL TU DE MUN TU DE MES❣️❣️")
        sleep(1)
        await e.edit("JASMIN CANTIK❣️")
        sleep(1)
        await e.edit("TAPI KADANG SUKA KEK KONTOL")
        sleep(1)
        await e.edit("SIPALING LAMA KALAU BALES CHAT")
        sleep(1)
        await e.edit("SIPALING BUDEG KALAU LAGI CALL")
        sleep(1)
        await e.edit("SIPALING RANDOM KALAU LAGI TYPING")
        sleep(1)
        await e.edit("TAPI INTINYA....")
        sleep(1)
        await e.edit("ICAL SAYANG JASMINE💞")


@register(outgoing=True, pattern='^.orgil(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ANJING ADA ORANG GILA.....`")
    sleep(1)
    await typew.edit("`ORANG GILAAAAAA!!`")
    sleep(1)
    await typew.edit("`🏃                        🤸`")
    await typew.edit("`🏃                       🤸`")
    await typew.edit("`🏃                      👨‍🦽`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃   `LARII`          🤾`")
    await typew.edit("`🏃                   🤾`")
    await typew.edit("`🏃                  🤾`")
    await typew.edit("`🏃                 🤾`")
    await typew.edit("`🏃                🤾`")
    await typew.edit("`🏃               🤺`")
    await typew.edit("`🏃              🏊`")
    await typew.edit("`🏃             🏊`")
    await typew.edit("`🏃            🏄`")
    await typew.edit("`🏃           🤾`")
    await typew.edit("`🏃PULUPULU   🧚`")
    await typew.edit("`🏃           ⛹️`")
    await typew.edit("`🏃            ⛹️`")
    await typew.edit("`🏃             🤺`")
    await typew.edit("`🏃              🥴`")
    await typew.edit("`🏃               🏃`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃                 🤸`")
    await typew.edit("`🏃                  🤸`")
    await typew.edit("`🏃                   🤸`")
    await typew.edit("`🏃                    🤸`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃  Huh-Huh           🏃`")
    await typew.edit("`🏃                   🤑`")
    await typew.edit("`🏃                  🙈`")
    await typew.edit("`🏃                 ⛹️`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃               🤴`")
    await typew.edit("`🏃              🐖`")
    await typew.edit("`🏃             🐖`")
    await typew.edit("`🏃            🥴`")
    await typew.edit("`🏃           🥴`")
    await typew.edit("`🏃          🤡`")
    await typew.edit("`🏃         🤭`")
    await typew.edit("`CAPE BANGET ANJING!!!`")
    sleep(1)
    await typew.edit("`🏃       🏃`")
    await typew.edit("`🏃      🤾`")
    await typew.edit("`🏃     🏃`")
    await typew.edit("`🏃    🏃`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🐖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern="^.jasmine$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`Woi ngentot cantik banget jasmine hari ini😱😱`")
        sleep(1)
        await e.edit("`Gila cantik banget ya allah>.< `")
        sleep(1)
        await e.edit("`Pacar siapa sih ini aarrghh>.<`")
        sleep(1)
        await e.edit("`AAAAA CBL CBL CBL❣️❣️`")
        sleep(1)
        await e.edit("`CANTIK BANGET LOCHH💛💞💖`")
        sleep(1)
        await e.edit("`Tolong.!!! cantik nya jasmine kelewatan>.<`")
        sleep(1)
        await e.edit("`KU BISA GILA KARNA JASMINE TERLALU CANTIK😱😱`")
        sleep(1)
        await e.edit("`KALIAN GABOLEH AMBIL JASMINE DARIKU 😡😡`")
        sleep(1)
        await e.edit("`Kalau diambil nanti aku sedih:'(`")
        sleep(1)
        await e.edit("🥺")
        await e.edit("😭")
        await e.edit("😔")
        await e.edit("😖")
        await e.edit("`POKOKNYA GABOLEH DI AMBIL😡`")
        await e.edit("💖")
        await e.edit("...........................🚐")
        await e.edit("..........................🚐.")
        await e.edit("..............🛺.........🚐..")
        await e.edit("..............🛺........🚐...")
        await e.edit("..............🛺.......🚐....")
        await e.edit("..............🛺......🚐.....")
        await e.edit("..............🛺.....🚐......")
        await e.edit("..............🛺....🚐.......")
        await e.edit("..............🛺...🚐........")
        await e.edit("..............🛺.🚐..........")
        await e.edit("..............🛺🚐...........")
        await e.edit("............🚐🛺.............")
        await e.edit("..........🚐...🛺............")
        await e.edit(".........🚐.....🛺...........")
        await e.edit("........🚐.......🛺..........")
        await e.edit(".......🚐..........🛺........")
        await e.edit("......🚐.............🛺......")
        await e.edit(".....🚐...............🛺.....")
        await e.edit("....🚐..................🛺...")
        await e.edit("..🚐.....................🛺..")
        await e.edit(".🚐........................🛺")
        await e.edit("🚐...........................")
        await e.edit("...........................🚐")
        await e.edit("........🏠🏡🏘️............🚐.")
        await e.edit("........🏘️🏡🏠...........🚐..")
        await e.edit("........🏘️🏡🏠..........🚐...")
        await e.edit("........🏘️🏡🏠.........🚐....")
        await e.edit("........🏘️🏘️🏘️........🚐.....")
        await e.edit("........🏡🏠🏡.......🚐......")
        await e.edit("........🏘️🏡🏠......🚐.......")
        await e.edit("........🏘️🏡🏠.....🚐........")
        await e.edit("........🏘️🏡🏠....🚐.........")
        await e.edit("........🏘️🏡🏠...🚐..........")
        await e.edit("........🏘️🏡🏠..🚐...........")
        await e.edit("........🏘️🏡🏠.🚐............")
        await e.edit("........🏘️🏡🏠🚐.............")
        await e.edit("........🏘️🏡🚐🏠.............")
        await e.edit("........🏘️🚐🏡🏠.............")
        await e.edit("........🚐🏠🏡🏘️.............")
        await e.edit(".......🚐.🏠🏡🏡.............")
        await e.edit("......🚐..🏘️🏡🏠.............")
        await e.edit(".....🚐...🏘️🏡🏠.............")
        await e.edit("....🚐....🏘️🏠🏡.............")
        await e.edit("...🚐.....🏠🏡🏘️.............")
        await e.edit("..🚐......🏘️🏡🏠.............")
        await e.edit(".🚐.......🏘️🏡🏠.............")
        await e.edit("🚐........🏠🏡🏘️.............")
        await e.edit("...........................🚐")
        await e.edit("............🕌............🚐.")
        await e.edit("............🕌...........🚐..")
        await e.edit("............🕌..........🚐...")
        await e.edit("............🕌.........🚐....")
        await e.edit("............🕌........🚐.....")
        await e.edit("............🕌.......🚐......")
        await e.edit("............🕌......🚐.......")
        await e.edit("............🕌.....🚐........")
        await e.edit("............🕌....🚐.........")
        await e.edit("............🕌...🚐..........")
        await e.edit("............🕌..🚐...........")
        await e.edit("............🕌.🚐............")
        await e.edit("............🕌🚐.............")
        await e.edit("............🚐🕌.............")
        await e.edit("...........🚐.🕌.............")
        await e.edit("..........🚐..🕌.............")
        await e.edit(".........🚐...🕌.............")
        await e.edit("........🚐....🕌ᴬᴸᴸᴬᴴᵁ ᴬᴷᴮᴬᴿ²ˣ.")
        await e.edit("ᵂᴬᴴ ᴬᴰᶻᴬᴺ🚐....🕌.............")
        await e.edit("ˢᴴᴼᴸᴬᵀ ᴬᴴ🚐....🕌.............")
        await e.edit(".........🚐...🕌............")
        await e.edit("...........🚐.🕌............")
        await e.edit("............🚐🕌............")
        await e.edit("CERITANYA LAGI SHOLAT")
        await e.edit("KARNA PENGEN JADI IMAM YANG BAIK BUAT JASMINE💞")
        await e.edit("KALAU LUPA SHOLAT NNT CALON MERTUA MARAH")
        await e.edit("KATA GANTENG NYA JASMINE")
        await e.edit("OTW LAGI KERUMAH JASMINE")
        await e.edit("ᴬᴸᴴᴬᴹᴰᵁᴸᴵᴸᴸᴬᴴ ᴰᴴ ᴷᴱᴸᴬᴿ🚐🕌.............")
        await e.edit("ᴮᴵˢᴹᴵᴸᴸᴬᴴ..........🚐.🕌.............")
        await e.edit("...............🚐..🕌.............")
        await e.edit("..............🚐...🕌.............")
        await e.edit(".............🚐....🕌.............")
        await e.edit("............🚐.....🕌.............")
        await e.edit("...........🚐......🕌.............")
        await e.edit("..........🚐.......🕌.............")
        await e.edit("🏘️.......🚐........🕌.............")
        await e.edit("🏘️......🚐.........🕌.............")
        await e.edit("🏘️.....🚐..........🕌.............")
        await e.edit("🏘️....🚐...........🕌.............")
        await e.edit("🏘️...🚐............🕌.............")
        await e.edit("🏘️..🚐.............🕌.............")
        await e.edit("🏘️.🚐..............🕌.............")
        await e.edit("🏘️🚐...............🕌.............")
        await e.edit("..............................🚐🏘️")
        await e.edit(".............................🚐.🏘️")
        await e.edit("............................🚐..🏘️")
        await e.edit("...........................🚐...🏘️")
        await e.edit("..........................🚐....🏘️")
        await e.edit(".........................🚐.....🏘️")
        await e.edit("........................🚐......🏘️")
        await e.edit(".......................🚐.......🏘️")
        await e.edit(".....................🚐.........🏘️")
        await e.edit("....................🚐..........🏘️")
        await e.edit("...................🚐...........🏘️")
        await e.edit("..................🚐............🏘️")
        await e.edit(".................🚐.............🏘️")
        await e.edit("................🚐..............🏘️")
        await e.edit("...............🚐...............🏘️")
        await e.edit("..............🚐................🏘️")
        await e.edit(".............🚐.................🏘️")
        await e.edit("............🚐..................🏘️")
        await e.edit("...........🚐...................🏘️")
        await e.edit("..........🚐....................🏘️")
        await e.edit(".........🚐.....................🏘️")
        await e.edit("........🚐......................🏘️")
        await e.edit(".......🚐.......................🏘️")
        await e.edit("......🚐........................🏘️")
        await e.edit(".....🚐.........................🏘️")
        await e.edit("....🚐..........................🏘️")
        await e.edit("...🚐...........................🏘️")
        await e.edit("..🚐............................🏘️")
        await e.edit(".🚐.............................🏘️")
        await e.edit("🚐..............................🏘️")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🏡🚶                              🐢")
        await e.edit("`DAH SAMPAU DIRUMAH AYANG JASMINE💞💖🧡💛❣️❤️`")


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`MAAF GADULU YA` **😝😜🤪😛** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting Ke Server Cinta`",
            "`Mencari Target Cinta`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim Padamu, Dan Sekarang Aku Sangat Mencintai Mu, I Love You 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.ass(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Salam dulu biar sopan....`")
    sleep(2)
    await typew.edit("`A`")
    await typew.edit("`As`")
    await typew.edit("`Ass`")
    await typew.edit("`Assa`")
    await typew.edit("`Assal`")
    await typew.edit("`Assala`")
    await typew.edit("`Assalam`")
    await typew.edit("`Assalamu`")
    await typew.edit("`Assalamu'a`")
    await typew.edit("`Assalamu'al`")
    await typew.edit("`Assalamu'ala`")
    await typew.edit("`Assalamu'alai`")
    await typew.edit("`Assalamu'alaik`")
    await typew.edit("`Assalamu'alaiku`")
    await typew.edit("`Assalamu'alaikum`")
    sleep(3)
    await typew.edit("**YANG GA JAWAB, FIX ATHEISS!!**")
   # Create by myself @ram-ubot

@register(outgoing=True, pattern='^.jj(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("WOI NGENTOT!!!")
    sleep(2)
    await typew.edit("TAU GA SIAPA CEWE YANG PALING CANTIK??")
    sleep(2)
    await typew.edit("YAUDAH PASTI JJ LAH GILA LO")
    sleep(2)
    await typew.edit("JJ SI PALING CANTIK")
    sleep(2)
    await typew.edit("JJ SI PALING MANIS")
    sleep(2)
    await typew.edit("JJ SIPALING PALING✨✨")
    sleep(2)
    await typew.edit("POKOKNYA YANG PALING CANTIK TU JJ YA ANJING.!!!")
    
    
CMD_HELP.update({
    "memes9":
    "`.jasmine` ; `.orgil`\
    \nUsage: ntahlah gabut doang.\
    \n\n`.ass`\
    \nUsage: Salam duls biar sopan."
})

CMD_HELP.update({
    "memes10":
    "`.cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`.jsmn` ;  `.jj`\
    \nUsage: cobalah sndiri ngentot."
})
